Repository kiosk-team-7/kiosk-max, pull requests merged in 2023-06, with the labels that each got.

#3 메인 화면 카테고리 탭 구현
  .gitignore
  client/.prettierrc
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.module.css
  client/src/App.tsx
  client/src/components/CategoryTab.module.css
  client/src/components/CategoryTab.tsx
  client/src/components/MenuList.tsx
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/styles/index.css
  client/src/styles/reset.css
  client/tsconfig.json
Labels: ✨ feature, FE

#11 메뉴 아이템 배치 구현
  client/src/App.module.css
  client/src/components/CategoryTab.module.css
  client/src/components/MenuItem.module.css
  client/src/components/MenuItem.tsx
  client/src/components/MenuList.module.css
  client/src/components/MenuList.tsx
  client/src/types/common.d.ts
Labels: ✨ feature, FE

#17 카테고리 서비스, 메뉴 레포지토리 클래스 구현
  be/src/main/java/kr/codesquad/kioskmax/domain/Menu.java
  be/src/main/java/kr/codesquad/kioskmax/repository/MenuRepository.java
  be/src/main/java/kr/codesquad/kioskmax/service/CategoryService.java
  be/src/main/java/kr/codesquad/kioskmax/service/dto/CategoryInformation.java
  be/src/main/java/kr/codesquad/kioskmax/service/dto/MenuInformation.java
  be/src/main/resources/application.yml
  be/src/test/java/kr/codesquad/kioskmax/repository/MenuRepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/service/CategoryServiceTest.java
  be/src/test/resources/data.sql
  be/src/test/resources/schema.sql
Labels: ✨ feature, BE

#19 메뉴 담기 모달 수량 카운터 컴포넌트 구현
  client/src/components/CartAdditionModal.module.css
  client/src/components/CartAdditionModal.tsx
Labels: ✨ feature, :art: Style, FE

#22 메뉴 리스트 애니메이션 구현
  client/src/App.tsx
  client/src/components/MenuList.tsx
Labels: ✨ feature, FE

#23 Collection 클래스 삭제, RestDocs 반영
  be/build.gradle
  be/src/docs/asciidoc/categories.adoc
  be/src/main/java/kr/codesquad/kioskmax/controller/dto/MenuResponse.java
  be/src/main/java/kr/codesquad/kioskmax/domain/Menu.java
  be/src/main/java/kr/codesquad/kioskmax/repository/MenuRepository.java
  be/src/main/java/kr/codesquad/kioskmax/service/dto/MenuInformation.java
  be/src/main/resources/static/docs/categories.html
  be/src/test/java/kr/codesquad/kioskmax/annotation/ControllerTest.java
  be/src/test/java/kr/codesquad/kioskmax/annotation/RepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/annotation/ServiceTest.java
  be/src/test/java/kr/codesquad/kioskmax/controller/CategoryControllerTest.java
  be/src/test/java/kr/codesquad/kioskmax/repository/CategoryRepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/repository/MenuRepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/service/CategoryServiceTest.java
  be/src/test/resources/data.sql
  be/src/test/resources/schema.sql
Labels: ✨ feature, BE

#27 메뉴 담기 모달 추가 기능 구현
  client/src/components/Main.tsx
  client/src/components/MenuAddModal.module.css
  client/src/components/MenuAddModal.tsx
  client/src/styles/reset.css
  client/src/types/commons.d.ts
  client/src/types/constants.ts
Labels: ✨ feature, FE

#29 CI/CD 기능 구현
  .github/workflows/auto-deploy.yml
  .gitignore
  appspec.yml
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/kr/codesquad/kioskmax/KioskMaxApplication.java
  be/src/main/java/kr/codesquad/kioskmax/controller/CategoryController.java
  be/src/main/java/kr/codesquad/kioskmax/controller/dto/CategoryResponse.java
  be/src/main/java/kr/codesquad/kioskmax/controller/dto/MenuResponse.java
  be/src/main/java/kr/codesquad/kioskmax/domain/Category.java
  be/src/main/java/kr/codesquad/kioskmax/domain/Menu.java
  be/src/main/java/kr/codesquad/kioskmax/repository/CategoryRepository.java
  be/src/main/java/kr/codesquad/kioskmax/repository/MenuRepository.java
  be/src/main/java/kr/codesquad/kioskmax/service/CategoryService.java
  be/src/main/java/kr/codesquad/kioskmax/service/dto/CategoryInformation.java
  be/src/main/java/kr/codesquad/kioskmax/service/dto/MenuInformation.java
  be/src/main/resources/application.yml
  be/src/test/java/kr/codesquad/kioskmax/KioskMaxApplicationTests.java
  be/src/test/java/kr/codesquad/kioskmax/annotation/ControllerTest.java
  be/src/test/java/kr/codesquad/kioskmax/annotation/RepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/annotation/ServiceTest.java
  be/src/test/java/kr/codesquad/kioskmax/controller/CategoryControllerTest.java
  be/src/test/java/kr/codesquad/kioskmax/repository/CategoryRepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/repository/MenuRepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/service/CategoryServiceTest.java
  be/src/test/resources/data.sql
  be/src/test/resources/schema.sql
  deploy.sh
Labels: ✨ feature, BE

#38 API 요청 URL 수정
  fe/db.json
  fe/package.json
  fe/routes.json
  fe/src/components/Home.tsx
Labels: 🥺 bug, FE

#39 장바구니 '전체 취소' 기능 구현
  fe/src/components/Cart.module.css
  fe/src/components/Cart.tsx
  fe/src/components/Main.tsx
Labels: ✨ feature, FE

#44 장바구니 개별 항목 삭제 기능 추가
  fe/src/components/Cart.tsx
  fe/src/components/Main.tsx
Labels: ✨ feature, FE

#47 커피 인기메뉴 기능 구현
  be/src/main/java/kr/codesquad/kioskmax/controller/dto/MenuResponse.java
  be/src/main/java/kr/codesquad/kioskmax/domain/Menu.java
  be/src/main/java/kr/codesquad/kioskmax/repository/MenuRepository.java
  be/src/main/java/kr/codesquad/kioskmax/service/dto/MenuInformation.java
  be/src/test/java/kr/codesquad/kioskmax/annotation/ControllerTest.java
  be/src/test/java/kr/codesquad/kioskmax/annotation/IntegrationTest.java
  be/src/test/java/kr/codesquad/kioskmax/controller/CategoryControllerTest.java
  be/src/test/java/kr/codesquad/kioskmax/controller/CategoryIntegrationTest.java
  be/src/test/java/kr/codesquad/kioskmax/repository/CategoryRepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/repository/MenuRepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/service/CategoryServiceTest.java
  be/src/test/resources/data.sql
  be/src/test/resources/schema.sql
  fe/db.json
  fe/package.json
  fe/routes.json
  fe/src/components/Cart.module.css
  fe/src/components/Cart.tsx
  fe/src/components/Home.tsx
  fe/src/components/Main.tsx
  fe/src/components/MenuAddModal.tsx
  fe/src/components/Modal.module.css
  fe/src/components/Modal.tsx
  fe/src/components/OptionButton.module.css
  fe/src/components/Payment.module.css
  fe/src/components/Payment.tsx
  fe/src/types/commons.d.ts
Labels: ✨ feature, BE

#50 feat #49: mock 서버 url 수정, interface 추가
  fe/src/components/Home.tsx
  fe/src/constants/index.ts
  fe/src/types/commons.d.ts
  fe/src/types/constants.ts
Labels: ✨ feature, FE

#51 현금 결제 모달 열기 기능
  fe/src/components/Cart.tsx
  fe/src/components/Modal.tsx
  fe/src/components/OptionButton.module.css
  fe/src/components/OptionButton.tsx
  fe/src/components/Payment.module.css
  fe/src/components/Payment.tsx
Labels: ✨ feature, :art: Style, FE

#57 현금 결제 스토리 구현
  fe/src/components/Cart.tsx
  fe/src/components/Payment.module.css
  fe/src/components/Payment.tsx
Labels: ✨ feature, :art: Style, FE

#59 테스트코드 DB 수정
  .github/workflows/auto-deploy.yml
  be/src/main/resources/application.yml
  be/src/test/java/kr/codesquad/kioskmax/annotation/IntegrationTest.java
  be/src/test/java/kr/codesquad/kioskmax/annotation/RepositoryTest.java
  be/src/test/java/kr/codesquad/kioskmax/repository/CategoryRepositoryTest.java
  be/src/test/resources/schema/data.sql
  be/src/test/resources/schema/schema.sql
  be/src/test/resources/schema/schema2.sql
Labels: ♻️ refactor, BE

#61 카드 결제 결과 스토리 구현
  fe/src/App.tsx
  fe/src/components/Cart.tsx
  fe/src/components/Payment.tsx
  fe/src/components/Result.module.css
  fe/src/components/Result.tsx
  fe/src/types/commons.d.ts
Labels: ✨ feature, FE

#64 현금 결제 결과 페이지로 이동 기능 구현
  fe/src/components/Cart.tsx
  fe/src/components/Payment.tsx
Labels: ✨ feature, FE

#67 feat #65: UI 개선
  fe/src/components/Cart.module.css
  fe/src/components/Cart.tsx
  fe/src/components/CategoryTab.module.css
  fe/src/components/Dim.module.css
  fe/src/components/MenuAddModal.module.css
  fe/src/components/MenuAddModal.tsx
  fe/src/components/MenuItem.tsx
  fe/src/components/MenuList.module.css
Labels: :art: Style, FE

#73 application-testDB 삭제
  be/src/main/resources/application-testDB.yml
Labels: ♻️ refactor, BE

#81 현재 보는 탭 클릭 시 상호작용 하지 않도록 수정
  fe/src/Pages/Home.tsx
Labels: 🥺 bug, FE
